// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sannel.House.Sprinklers.Features.Common;

#nullable disable

namespace Sannel.House.Sprinklers.Features.Common.Migrations
{
    [DbContext(typeof(SprinklerDbContext))]
    partial class ScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Sannel.House.Sprinklers.Features.Logs.StationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActionDate")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("RunLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<byte>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RunLog");
                });

            modelBuilder.Entity("Sannel.House.Sprinklers.Features.Schedules.ScheduleProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("IntervalStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Sannel.House.Sprinklers.Features.Schedules.ZoneRun", b =>
                {
                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<byte>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ran")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("RunLength")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("StartDateTime", "ZoneId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Sannel.House.Sprinklers.Features.Zones.ZoneMetaData", b =>
                {
                    b.Property<byte>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ZoneId");

                    b.ToTable("ZoneMetaDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
