# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "main"
      - "develop"
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main", "develop" ]

env:
  major: 0
  minor: 1
  patch: 0

jobs:
  x64:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          # list of Docker images to use as base name for tags
          images: |
            sannel/house.sprinklers:linux-x64            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=${{ env.major }}.${{ env.minor }}.${{ env.patch }}
            type=sha            
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: FixTags
      id: fixedTags
      run: |
        fixed=$(echo "${{ steps.meta.outputs.tags }}" | sed 's/:/:linux-x64./g')
        export tags="$fixed"
      
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          build-args: |
            Major=${{ env.major }}
            Minor=${{ env.minor }}
            Patch=${{ env.patch }}
            BuildNumber=${{ github.run_number }}
          file: src/Sannel.House.Sprinklers/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.fixedTags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  arm64:
    runs-on: [self-hosted, ARM64]
    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          # list of Docker images to use as base name for tags
          images: |
            sannel/house.sprinklers            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=sha            
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          build-args: |
            Major=${{ env.major }}
            Minor=${{ env.minor }}
            Patch=${{ env.patch }}
            BuildNumber=${{ github.run_number }}
          file: src/Sannel.House.Sprinklers/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  combine:
    runs-on: [self-hosted, ARM64]
    needs:
    - x64
    - arm64
    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          # list of Docker images to use as base name for tags
          images: |
            sannel/house.sprinklers            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=sha            
