# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "main"
      - "develop"
      - feature/*
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main", "develop" ]

env:
  major: 0
  minor: 2
  patch: 0

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          # list of Docker images to use as base name for tags
          images: |
            sannel/house.sprinklers            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=v${{ env.major }}.${{ env.minor }}.${{ env.patch }}.${{ github.run_number }}
            type=ref,event=branch
            type=ref,event=pr
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
          platforms: arm64
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          build-args: |
            Major=${{ env.major }}
            Minor=${{ env.minor }}
            Patch=${{ env.patch }}
            BuildNumber=${{ github.run_number }}
          file: src/Sannel.House.Sprinklers/Dockerfile
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  nuget:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 8.0 SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: .NET Restore
      run: dotnet restore src/Sannel.House.Sprinklers.Shared/Sannel.House.Sprinklers.Shared.csproj
    - name: .NET build
      run: dotnet build --no-restore src/Sannel.House.Sprinklers.Shared/Sannel.House.Sprinklers.Shared.csproj
    - name: .NET pack
      run: dotnet pack src/Sannel.House.Sprinklers.Shared/Sannel.House.Sprinklers.Shared.csproj -o ./publish
    - name: .NET push to github
      run: dotnet nuget push ./publish/*.nupkg --source "https://nuget.pkg.github.com/Sannel/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: nuget 
        path: ./publish
  nuget_org:
    runs-on: ubuntu-24.04
    environment: "nuget.org"
    needs: nuget
    steps:
    - uses: actions/download-artifact@v4
    - name: .NET push to nuget
      run: dotnet nuget push ./publish/*.nupkg --api-key ${{ secrets.NUGET_API_TOKEN }}

